### ISSUE TITLE
ask about the downstream application

### ISSUE THREAD

**Issue by lenka844** [xyupeng/ContrastiveCrop#10]
Thanks for sharing your great job! when i finish the pretext task in my own dataset, i got a checkpoint file, i check the keys in that file, it conbines statedict and boxes, i was confused about the box information is useful in the downstream task? or should i also consider to load the box weight?

**Comment by xyupeng** [comment]
No. box info is only used in pretraining. For downstream tasks, only model weights are useful.

**Comment by lenka844** [comment]
> No. box info is only used in pretraining. For downstream tasks, only model weights are useful.
Thanks for your answer! Have a nice day.
