### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cymdhx** [xyupeng/ContrastiveCrop#12]

**Comment by cymdhx** [comment]
请问 这个可以用在目标检测上吗。

**Comment by cymdhx** [comment]
我还想请教下怎么使用ContrastiveCrop
我看代码里是这个ContrastiveCrop(alpha=alpha, size=224, scale=(0.2, 1.0)),我想问img和box参数是怎么传进去的呢

**Comment by xyupeng** [comment]
Yes. Pretraining a model with ContrastiveCrop could potentially improve downstream detection tasks.
Boxes are stored in the dataset, which are passed to ContrastiveCrop as well as other transformations along with imgs. [See here](https://github.com/xyupeng/ContrastiveCrop/blob/6bd54c433dd05e817cd3d3adcd7d61b4bb12c811/datasets/cifar.py#L20)
