### ISSUE TITLE
More models and datasets coming soon?

### ISSUE THREAD

**Issue by DWCTOD** [xyupeng/ContrastiveCrop#19]
你好，请问后续会更新模型的权重和数据集吗？
另外想请问一下大佬，关于对比学习，如何去评价模型embedding是否学的“够好”（表征能力）？好像一般是根据下游任务去评价的，但是有些任务很难去定义这样子的任务。例如业务场景是那种社媒的？

**Comment by xyupeng** [comment]
后续更新可能还需要一段时间。表征能力的评估在cv领域一般有分类linear probing，检测/分割fine-tune, partial fine-tune, freeze backbone等等。一般来说预训练的表征够好，则在下游任务上的初期收敛速度较快。

**Comment by DWCTOD** [comment]
谢谢大佬的解答，感谢
