### ISSUE TITLE
ContrastiveCrop的size和scale是根据数据集设定吗，还是代码中的size=32，scale=（0.2,1.0）适配所有数据集

### ISSUE THREAD

**Issue by syfffffff** [xyupeng/ContrastiveCrop#2]

**Comment by xyupeng** [comment]
The size should vary based on the dataset. size=32 is the typical size used for CIFAR-10/100.
The scale is relatively less important. scale=(0.2, 1.0) should be a good default for different datasets. Of course, you can try a different lower/upper bound for parameter tuning.

**Comment by syfffffff** [comment]
If my picture size is 224 * 224, can I increase my size appropriately

**Comment by xyupeng** [comment]
Of course, you can set size=224. Note that the size passed to `ContrastiveCrop` is the same as the one passed to `RandomResizedCrop`.

**Comment by syfffffff** [comment]
thanks
