### ISSUE TITLE
请问ContrastiveCrop的ratio的参数是多少？

### ISSUE THREAD

**Issue by leo-hao** [xyupeng/ContrastiveCrop#5]
在ContrastiveCrop(alpha=alpha, size=224, scale=(0.2, 1.0))里面没有设置ratio，请问这个参数怎么设置

**Comment by xyupeng** [comment]
We use the default ratio=(3/4, 4/3) of RandomResizedCrop. You can simply pass ratio=(a, b) to ContrastiveCrop().
