### ISSUE TITLE
How can I use it for downstream tasks

### ISSUE THREAD

**Issue by 123456789-qwer** [xyupeng/ContrastiveCrop#6]
If I want to use representation information for downstream tasks, which part of the feature should I use  ？

**Comment by xyupeng** [comment]
For linear classification, please follow README. For object detection and instance segmentation, we use the same code as in [MoCo](https://github.com/facebookresearch/moco/tree/main/detection).

**Comment by 123456789-qwer** [comment]
I still haven't found how the pre-training model is used for target detection, could you give a specific explanation

**Comment by xyupeng** [comment]
Transferring to detection is the same as [MoCo](https://github.com/facebookresearch/moco/tree/main/detection).

**Comment by xyupeng** [comment]
To be more specific, you need to first convert the saved model (last.pth) to detectron2's format. Then use detectron2's code to train detection.
