### ISSUE TITLE
dataloader and updating the box

### ISSUE THREAD

**Issue by DanielaPlusPlus** [xyupeng/ContrastiveCrop#7]
Hi, great work! Thank you for sharing.
In the codes, training data is loaded after the contrastive crop and then is used for training through all epochs. 
And for every location interval epoch,  the box is updated.
The box is used for the contrastive crop in the data loader process to generate better sample pairs.
So how is the updating of the box used for generating better sample pairs?  
I guess maybe we should load the training data every time we update the box, what do you think?

**Comment by xyupeng** [comment]
Hi,
The key is not the dataloader, but the dataset.
The dataset holds the box information for every sample, which is used by `ContrastiveCrop` to generate better views. And the boxes are updated at some interval.

**Comment by DanielaPlusPlus** [comment]
How will the updated box be used for the dataset?
In the codes, [the dataset is loaded](https://github.com/xyupeng/ContrastiveCrop/blob/966f1addc5f2eed1c1db7430d9234c8d656decd1/DDP_moco_ccrop.py#L225) out of the epochs cycling with the initial box,  [the updating of the box](https://github.com/xyupeng/ContrastiveCrop/blob/966f1addc5f2eed1c1db7430d9234c8d656decd1/DDP_moco_ccrop.py#L275) is in the epochs cycling. How will the updating of the box affect the dataset?

**Comment by DanielaPlusPlus** [comment]
Sorry, I got it.  It's solved. The updating is used  [here ](https://github.com/xyupeng/ContrastiveCrop/blob/966f1addc5f2eed1c1db7430d9234c8d656decd1/DDP_moco_ccrop.py#L278)
